language: go
go:
    - 1.7
before_install:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
    - go get gopkg.in/yaml.v1
    - go get github.com/gorilla/handlers
    - go get github.com/gorilla/mux
script:
    - go test -v -covermode=count -coverprofile=coverage.out
      #- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
    - $HOME/gopath/bin/goveralls -service=travis-ci

